version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: my_User
      POSTGRES_PASSWORD: qqpp
      POSTGRES_DB: rates  # ← Добавь базу данных
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mymail.ru
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8081:80  # ← Исправлено: 8081 вместо 8080
    networks:
      - postgres
    restart: unless-stopped

  app:  # ← Твой Go-сервер
    container_name: usd_rub_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://my_User:qqpp@postgres:5432/rates?sslmode=disable
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: